# Generated by Django 2.2.dev20180908154613 on 2019-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190604_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
