# Generated by Django 2.2.dev20180908154613 on 2019-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190608_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_rating',
            name='ISBN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='User_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book_view',
            name='ISBN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book_view',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
