# Generated by Django 2.2.dev20180908154613 on 2019-06-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_rating',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User_data'),
        ),
        migrations.AlterField(
            model_name='book_view',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User_data'),
        ),
    ]
